require '../../podfile_tool'

platform :ios, '10.0'

target 'AnotherAppShareExtension' do
  use_frameworks!
end

target 'AppShareExtension' do
  use_frameworks!
end

target 'DummyRemoveTarget' do
  use_frameworks!
end

post_integrate do |installer|
  PodfileTool.remove_dependency_targets!(__FILE__, ["AnotherAppShareExtension", "AppShareExtension"] , "DummyRemoveTarget", false, true)
end
